version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-app-price-fetcher:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - web

networks:
  web: